/**
 * Auto-generated by tools/scan-images.mjs — do not edit manually.
 * Run `npm run scan` to regenerate from public/ folder contents.
 */

export interface CategoryPhoto {
  id: string;
  src: string;
  alt: string;
  aspect?: "landscape" | "portrait" | "square";
}

export interface CategoryDetail {
  id: string;
  name: string;
  description: string;
  photos: CategoryPhoto[];
}

export const categoryDetails: Record<string, CategoryDetail> = {
  landscapes: {
    id: "landscapes",
    name: "Landscapes",
    description:
      "Exploring the raw beauty of mountains, valleys, and open skies — chasing light across vast horizons.",
    photos: [
      {
        id: "l1",
        src: "/landscapes/01.jpg",
        alt: "01",
        aspect: "landscape",
      },
    ],
  },
  nature: {
    id: "nature",
    name: "Nature",
    description:
      "Intimate moments with flora and fauna — the quiet poetry of the natural world.",
    photos: [
      {
        id: "n1",
        src: "/nature/01.jpg",
        alt: "01",
        aspect: "portrait",
      },
      {
        id: "n2",
        src: "/nature/02.jpg",
        alt: "02",
        aspect: "landscape",
      },
      {
        id: "n3",
        src: "/nature/03.jpg",
        alt: "03",
        aspect: "portrait",
      },
      {
        id: "n4",
        src: "/nature/04.jpg",
        alt: "04",
        aspect: "landscape",
      },
      {
        id: "n5",
        src: "/nature/05.jpg",
        alt: "05",
        aspect: "landscape",
      },
      {
        id: "n6",
        src: "/nature/06.jpg",
        alt: "06",
        aspect: "landscape",
      },
      {
        id: "n7",
        src: "/nature/07.jpg",
        alt: "07",
        aspect: "landscape",
      },
      {
        id: "n8",
        src: "/nature/08.jpg",
        alt: "08",
        aspect: "portrait",
      },
      {
        id: "n9",
        src: "/nature/09.jpg",
        alt: "09",
        aspect: "portrait",
      },
      {
        id: "n10",
        src: "/nature/10.jpg",
        alt: "10",
        aspect: "landscape",
      },
      {
        id: "n11",
        src: "/nature/11.jpg",
        alt: "11",
        aspect: "landscape",
      },
    ],
  },
  street: {
    id: "street",
    name: "Street",
    description:
      "Candid stories from sidewalks and alleyways — the choreography of everyday life.",
    photos: [
      {
        id: "s1",
        src: "/street/01.jpg",
        alt: "01",
        aspect: "portrait",
      },
      {
        id: "s2",
        src: "/street/02.jpg",
        alt: "02",
        aspect: "portrait",
      },
      {
        id: "s3",
        src: "/street/03.jpg",
        alt: "03",
        aspect: "portrait",
      },
      {
        id: "s4",
        src: "/street/04.jpg",
        alt: "04",
        aspect: "portrait",
      },
    ],
  },
  architecture: {
    id: "architecture",
    name: "Architecture",
    description:
      "Forms, lines, and light — the silent dialogue between structure and space.",
    photos: [
      {
        id: "a1",
        src: "/architecture/01.jpg",
        alt: "01",
        aspect: "landscape",
      },
      {
        id: "a2",
        src: "/architecture/02.jpg",
        alt: "02",
        aspect: "portrait",
      },
      {
        id: "a3",
        src: "/architecture/03.jpg",
        alt: "03",
        aspect: "portrait",
      },
    ],
  },
  travel: {
    id: "travel",
    name: "Travel",
    description:
      "Visual postcards from wandering — the feeling of being somewhere new for the first time.",
    photos: [
      {
        id: "t1",
        src: "/travel/01.jpg",
        alt: "01",
        aspect: "portrait",
      },
      {
        id: "t2",
        src: "/travel/02.jpg",
        alt: "02",
        aspect: "portrait",
      },
      {
        id: "t3",
        src: "/travel/03.jpg",
        alt: "03",
        aspect: "landscape",
      },
    ],
  },
};
