/**
 * Auto-generated by tools/scan-images.mjs — do not edit manually.
 * Run `npm run scan` to regenerate from public/ folder contents.
 */

export const images = {
  hero: "/landscapes/01.jpg",
  about: "/nature/01.jpg",
};

export interface CategoryConfig {
  id: string;
  name: string;
  count: number;
  cover: string;
}

export const categories: CategoryConfig[] = [
  {
    id: "landscapes",
    name: "Landscapes",
    count: 1,
    cover: "/landscapes/01.jpg",
  },
  {
    id: "nature",
    name: "Nature",
    count: 11,
    cover: "/nature/01.jpg",
  },
  {
    id: "street",
    name: "Street",
    count: 4,
    cover: "/street/01.jpg",
  },
  {
    id: "architecture",
    name: "Architecture",
    count: 3,
    cover: "/architecture/01.jpg",
  },
  {
    id: "travel",
    name: "Travel",
    count: 3,
    cover: "/travel/01.jpg",
  },
];
