#!/usr/bin/env node
/**
 * scan-images.mjs — Auto-generate image config from public/ folder contents.
 *
 * Scans public/<category>/ directories, detects aspect ratios via `sips`,
 * and writes:
 *   - src/config/categoryImages.ts  (photo arrays per category)
 *   - src/config/images.ts          (hero, about, covers, counts)
 *
 * Usage:  node tools/scan-images.mjs
 *         npm run scan
 */

import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const PUBLIC_DIR = path.join(ROOT, "public");
const CATEGORY_IMAGES_FILE = path.join(ROOT, "src/config/categoryImages.ts");
const IMAGES_FILE = path.join(ROOT, "src/config/images.ts");

const CATEGORIES = [
  { id: "landscapes", name: "Landscapes", prefix: "l", description: "Exploring the raw beauty of mountains, valleys, and open skies — chasing light across vast horizons." },
  { id: "nature", name: "Nature", prefix: "n", description: "Intimate moments with flora and fauna — the quiet poetry of the natural world." },
  { id: "street", name: "Street", prefix: "s", description: "Candid stories from sidewalks and alleyways — the choreography of everyday life." },
  { id: "architecture", name: "Architecture", prefix: "a", description: "Forms, lines, and light — the silent dialogue between structure and space." },
  { id: "travel", name: "Travel", prefix: "t", description: "Visual postcards from wandering — the feeling of being somewhere new for the first time." },
];

function getImageDimensions(filePath) {
  try {
    const out = execSync(`sips -g pixelWidth -g pixelHeight "${filePath}"`, {
      encoding: "utf8",
      stdio: ["pipe", "pipe", "pipe"],
    });
    const w = parseInt(out.match(/pixelWidth:\s*(\d+)/)?.[1] || "0");
    const h = parseInt(out.match(/pixelHeight:\s*(\d+)/)?.[1] || "0");
    return { width: w, height: h };
  } catch {
    return { width: 0, height: 0 };
  }
}

function detectAspect(w, h) {
  if (w === 0 || h === 0) return "landscape";
  const ratio = w / h;
  if (ratio > 1.15) return "landscape";
  if (ratio < 0.85) return "portrait";
  return "square";
}

function altFromFilename(filename) {
  return filename
    .replace(/\.[^.]+$/, "")
    .replace(/[_-]/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function scanCategory(categoryId) {
  const catDir = path.join(PUBLIC_DIR, categoryId);
  if (!fs.existsSync(catDir)) return [];

  const files = fs
    .readdirSync(catDir)
    .filter((f) => !f.startsWith("._") && /\.(jpe?g|png|webp)$/i.test(f))
    .sort();

  return files.map((filename) => {
    const filePath = path.join(catDir, filename);
    const { width, height } = getImageDimensions(filePath);
    const aspect = detectAspect(width, height);
    const alt = altFromFilename(filename);
    return { filename, src: `/${categoryId}/${filename}`, alt, aspect };
  });
}

// ── Generate categoryImages.ts ───────────────────────────────────────────────

function generateCategoryImagesTS() {
  const sections = [];

  for (const cat of CATEGORIES) {
    const photos = scanCategory(cat.id);
    const photoEntries = photos
      .map((p, i) => {
        const id = `${cat.prefix}${i + 1}`;
        return `      {
        id: "${id}",
        src: "${p.src}",
        alt: "${p.alt.replace(/"/g, '\\"')}",
        aspect: "${p.aspect}",
      }`;
      })
      .join(",\n");

    sections.push(`  ${cat.id}: {
    id: "${cat.id}",
    name: "${cat.name}",
    description:
      "${cat.description}",
    photos: [
${photoEntries},
    ],
  }`);
  }

  return `/**
 * Auto-generated by tools/scan-images.mjs — do not edit manually.
 * Run \`npm run scan\` to regenerate from public/ folder contents.
 */

export interface CategoryPhoto {
  id: string;
  src: string;
  alt: string;
  aspect?: "landscape" | "portrait" | "square";
}

export interface CategoryDetail {
  id: string;
  name: string;
  description: string;
  photos: CategoryPhoto[];
}

export const categoryDetails: Record<string, CategoryDetail> = {
${sections.join(",\n")},
};
`;
}

// ── Generate images.ts ───────────────────────────────────────────────────────

function generateImagesTS() {
  const categoryEntries = CATEGORIES.map((cat) => {
    const photos = scanCategory(cat.id);
    const cover = photos.length > 0 ? photos[0].src : `/${cat.id}/01.jpg`;
    return `  {
    id: "${cat.id}",
    name: "${cat.name}",
    count: ${photos.length},
    cover: "${cover}",
  }`;
  });

  // Pick hero and about images from available photos
  const allPhotos = CATEGORIES.flatMap((cat) =>
    scanCategory(cat.id).map((p) => ({ ...p, category: cat.id }))
  );
  const heroPhoto = allPhotos.find((p) => p.aspect === "landscape") || allPhotos[0];
  const aboutPhoto =
    allPhotos.find((p) => p.category !== heroPhoto?.category) || allPhotos[1] || allPhotos[0];

  const heroSrc = heroPhoto?.src || "/landscapes/01.jpg";
  const aboutSrc = aboutPhoto?.src || "/nature/01.jpg";

  return `/**
 * Auto-generated by tools/scan-images.mjs — do not edit manually.
 * Run \`npm run scan\` to regenerate from public/ folder contents.
 */

export const images = {
  hero: "${heroSrc}",
  about: "${aboutSrc}",
};

export interface CategoryConfig {
  id: string;
  name: string;
  count: number;
  cover: string;
}

export const categories: CategoryConfig[] = [
${categoryEntries.join(",\n")},
];
`;
}

// ── Main ─────────────────────────────────────────────────────────────────────

console.log("Scanning public/ for images...\n");

for (const cat of CATEGORIES) {
  const photos = scanCategory(cat.id);
  console.log(`  ${cat.name.padEnd(14)} ${photos.length} image(s)`);
}

const categoryImagesContent = generateCategoryImagesTS();
const imagesContent = generateImagesTS();

fs.writeFileSync(CATEGORY_IMAGES_FILE, categoryImagesContent, "utf8");
fs.writeFileSync(IMAGES_FILE, imagesContent, "utf8");

console.log(`\n  ✓ wrote ${CATEGORY_IMAGES_FILE.replace(ROOT + "/", "")}`);
console.log(`  ✓ wrote ${IMAGES_FILE.replace(ROOT + "/", "")}`);
console.log("\nDone! Config files are up to date.\n");
